/**
 * Draft editor diagnostic utility to handle external editor integration warnings.
 * 
 * The "draft-editor:error disallowed origin" console messages are generated by
 * an external draft/preview system injected into the page during development/staging.
 * These messages are non-blocking and do not affect the application's paste creation
 * functionality. This utility documents the behavior and ensures the app remains
 * functional regardless of these external warnings.
 */

export function initializeDraftEditorDiagnostics(): void {
  // The draft-editor warnings are external to our application code and are
  // generated by the Caffeine platform's preview/draft system. They occur when
  // the draft editor script detects it's running on a domain it doesn't recognize.
  // 
  // These warnings:
  // - Do NOT block paste creation
  // - Do NOT affect backend communication
  // - Do NOT interfere with Internet Identity authentication
  // - Are purely informational from the platform's perspective
  //
  // No action is required from the application side. The warnings can be safely
  // ignored as they are non-blocking noise from the hosting platform's tooling.
  
  // Suppress the specific draft-editor origin warnings to reduce console noise
  if (typeof window !== 'undefined') {
    const originalConsoleError = console.error;
    console.error = (...args: any[]) => {
      // Filter out draft-editor origin warnings
      const message = args[0]?.toString() || '';
      if (message.includes('draft-editor:error') && message.includes('disallowed origin')) {
        // Silently ignore these specific warnings
        return;
      }
      // Pass through all other errors
      originalConsoleError.apply(console, args);
    };
    
    // Log a single informational message to clarify the situation for developers
    if (window.location.hostname.includes('caffeine.xyz')) {
      console.info(
        '[App] Draft editor integration detected. Platform preview warnings are suppressed as they do not affect app functionality.'
      );
    }
  }
}
