/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type ExternalBlob = Uint8Array;
export interface FileChunk {
  'contentType' : [] | [string],
  'data' : ExternalBlob,
  'filename' : string,
}
export interface Paste {
  'owner' : [] | [Principal],
  'password' : [] | [string],
  'expirationTime' : bigint,
  'items' : Array<PasteChunk>,
}
export type PasteChunk = { 'file' : FileChunk } |
  { 'text' : string };
export type PasteChunkType = { 'file' : null } |
  { 'text' : null };
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'clearAllPastes' : ActorMethod<[], undefined>,
  'clearLegacyIdMap' : ActorMethod<[], undefined>,
  'clearUserProfiles' : ActorMethod<[], undefined>,
  'createPaste' : ActorMethod<
    [Array<PasteChunk>, string, [] | [string]],
    string
  >,
  'deleteExpiredPastes' : ActorMethod<[], undefined>,
  'deletePaste' : ActorMethod<[string], undefined>,
  'editPaste' : ActorMethod<[string, Array<PasteChunk>], undefined>,
  'extendExpiration' : ActorMethod<[string, string, [] | [string]], undefined>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getFileData' : ActorMethod<
    [string, [] | [string], bigint],
    [] | [FileChunk]
  >,
  'getFileMetadata' : ActorMethod<
    [string, [] | [string]],
    Array<[string, [] | [string]]>
  >,
  'getPassword' : ActorMethod<[string], [] | [string]>,
  'getPaste' : ActorMethod<[string, [] | [string]], [] | [Paste]>,
  'getPasteChunk' : ActorMethod<
    [string, [] | [string], bigint],
    [] | [PasteChunk]
  >,
  'getPasteChunksWithTypes' : ActorMethod<
    [string, [] | [string]],
    Array<[PasteChunk, PasteChunkType]>
  >,
  'getPasteHistory' : ActorMethod<[], [] | [Array<[string, Paste]>]>,
  'getRemainingTime' : ActorMethod<[string], bigint>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isPasteOwner' : ActorMethod<[string], boolean>,
  'listActivePastes' : ActorMethod<[], Array<string>>,
  'listMyPastes' : ActorMethod<[], Array<string>>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'saveFile' : ActorMethod<[ExternalBlob, string, [] | [string]], FileChunk>,
  'systemDefaultCheck' : ActorMethod<[], undefined>,
  'systemDefaultReset' : ActorMethod<[], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];